<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="0.14.0" />
    <PackageReference Include="AngleSharp.ContentExtraction" Version="0.0.2" />
    <PackageReference Include="AngleSharp.Io" Version="0.14.0" />
    <PackageReference Include="AngleSharp.Js" Version="0.14.0" />
    <PackageReference Include="morelinq" Version="3.3.2" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="RestSharp" Version="106.11.4" />
    <PackageReference Include="Selenium.Chrome.WebDriver" Version="83.0.0" />
    <PackageReference Include="Selenium.WebDriver" Version="3.141.0" />
    <PackageReference Include="ServiceStack.Text" Version="5.9.0" />
  </ItemGroup>

</Project>
