<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>0.0.7</Version>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AngleSharp" Version="0.14.0" />
        <PackageReference Include="AngleSharp.ContentExtraction" Version="0.0.2" />
        <PackageReference Include="AngleSharp.Io" Version="0.14.0" />
        <PackageReference Include="AngleSharp.Js" Version="0.14.0" />
        <PackageReference Include="EmbedIO" Version="3.4.3" />
        <PackageReference Include="HtmlAgilityPack" Version="1.12.2" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.7" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.7" />
        <PackageReference Include="morelinq" Version="3.3.2" />
        <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
        <PackageReference Include="Polly" Version="8.6.2" />
        <PackageReference Include="RestSharp" Version="112.1.0" />
        <PackageReference Include="ReverseMarkdown" Version="4.7.0" />
        <PackageReference Include="Selenium.Chrome.WebDriver" Version="85.0.0" />
        <PackageReference Include="Selenium.WebDriver" Version="4.34.0" />
        <PackageReference Include="ServiceStack.Text" Version="5.9.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\RestSharp.Extensions\RestSharp.Polly.Extensions.Core.csproj" />
    </ItemGroup>
</Project>
