<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>0.0.7</Version>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="tls-client-sharp" Version="1.0.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.7" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.7" />
        <PackageReference Include="Polly" Version="8.6.2" />
        <PackageReference Include="RestSharp" Version="112.1.0" />
        <PackageReference Include="Selenium.WebDriver" Version="4.34.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Funny.WebScrape.Core\Funny.WebScrape.Core.csproj" />
      <ProjectReference Include="..\RestSharp.Extensions\RestSharp.Polly.Extensions.Core.csproj" />
    </ItemGroup>

</Project>
